/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////


/** Computes the 16-bit CRC used to validate FIT file headers and file data. */
export class CrcCalculator {
    constructor();
    /** The current running CRC value. */
    readonly crc: number;
    /**
     * Feeds a range of bytes into the running CRC.
     * @param buf - The byte array to process.
     * @param start - Inclusive start index within `buf`.
     * @param end - Exclusive end index within `buf`.
     * @returns The updated CRC value.
     */
    addBytes(buf: Uint8Array, start: number, end: number): number;
    /**
     * Computes the CRC for a range of bytes without requiring an instance.
     * @param buf - The byte array to process.
     * @param start - Inclusive start index within `buf`.
     * @param end - Exclusive end index within `buf`.
     * @returns The computed CRC value.
     */
    static calculateCRC(buf: Uint8Array, start: number, end: number): number;
}
