/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////


import Types from "./types";

/** A FIT field value — a scalar or array of one of the primitive FIT base types. */
export type FieldValue =
    | string
    | number
    | boolean
    | bigint
    | Date
    | (string | number | boolean | bigint | Date)[];

/** Developer-defined fields keyed by developer field key. */
export type DeveloperFields = { [developerFieldKey: string]: FieldValue | undefined };

/** Base interface for all decoded FIT messages. */
export interface Mesg {
    /** Global FIT message number identifying the message type. */
    mesgNum?: Types.MesgNum;
    /** Developer-defined field values attached to this message. */
    developerFields?: DeveloperFields;
}

export type Encodable<T extends Mesg> = T & Required<Pick<Mesg, 'mesgNum'>>;
