/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////


export type FitBaseTypeString =
    | 'enum'
    | 'byte'
    | 'sint8'
    | 'uint8'
    | 'uint8z'
    | 'sint16'
    | 'uint16'
    | 'uint16z'
    | 'sint32'
    | 'uint32'
    | 'uint32z'
    | 'sint64'
    | 'uint64'
    | 'uint64z'
    | 'float64'
    | 'float32'
    | 'string';

/** A reference mapping a subfield's activation value to its controlling field name */
export interface SubFieldMap {
    name: string;
    value: number;
}

/** A subfield that is active when a controlling field matches a specific value */
export interface ProfileSubField {
    name: string;
    type: string;
    baseType: FitBaseTypeString;
    scale: number | number[];
    offset: number | number[];
    units: string | string[];
    bits: number[];
    components: string[];
    hasComponents: boolean;
    map: SubFieldMap[];
}

/** A field definition within a profile message */
export interface ProfileField {
    num: number;
    name: string;
    type: string;
    baseType: FitBaseTypeString;
    array: boolean;
    scale: number | number[];
    offset: number | number[];
    units: string | string[];
    bits: number[];
    components: string[];
    isAccumulated: boolean;
    hasComponents: boolean;
    subFields: ProfileSubField[];
}

/** A message definition from the FIT profile */
export interface ProfileMesg {
    num: number;
    name: string;
    messagesKey: string;
    fields: Record<number, ProfileField>;
}

export declare const Profile: {
    /** The FIT profile version */
    readonly version: {
        major: number;
        minor: number;
        patch: number;
        type: string;
    };
    readonly CommonFields: {
        readonly PartIndex: number;
        readonly Timestamp: number;
        readonly MessageIndex: number;
    };
    /** All profile messages keyed by message number */
    readonly messages: Record<number, ProfileMesg>;
    /** All profile types keyed by type name, then value */
    readonly types: Record<string, Record<number, string>>;
    /** Message number constants keyed by message name */
    readonly MesgNum: Record<string, number>;
};
