/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////


export declare const Utils: {
    /** Millisecond offset between the UNIX epoch (1970-01-01) and the FIT epoch (1989-12-31): `631065600000`. */
    readonly FIT_EPOCH_MS: number;

    /**
     * Converts a FIT DateTime value to a JavaScript `Date`.
     * @param datetime - Seconds since the FIT epoch (1989-12-31 00:00:00 UTC).
     * @returns The equivalent JavaScript `Date`.
     */
    convertDateTimeToDate(datetime: number): Date;

    /**
     * Converts a JavaScript `Date` to a FIT DateTime value.
     * @param date - The JavaScript `Date` to convert.
     * @returns Seconds since the FIT epoch (1989-12-31 00:00:00 UTC).
     */
    convertDateToDateTime(date: Date): number;

    /** FIT base type numeric constants. */
    readonly FitBaseType: {
        readonly ENUM: number;
        readonly SINT8: number;
        readonly UINT8: number;
        readonly SINT16: number;
        readonly UINT16: number;
        readonly SINT32: number;
        readonly UINT32: number;
        readonly STRING: number;
        readonly FLOAT32: number;
        readonly FLOAT64: number;
        readonly UINT8Z: number;
        readonly UINT16Z: number;
        readonly UINT32Z: number;
        readonly BYTE: number;
        readonly SINT64: number;
        readonly UINT64: number;
        readonly UINT64Z: number;
    };
    /** Maps a FIT base type number to its string field-type name (e.g. `3` → `"uint8"`). */
    readonly BaseTypeToFieldType: Record<number, string>;
    /** Maps a FIT field-type name to its base type number (e.g. `"uint8"` → `3`). */
    readonly FieldTypeToBaseType: Record<string, number>;
};
