/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.194.0Release
// Tag = production/release/21.194.0-0-g65135fc
/////////////////////////////////////////////////////////////////////////////////////////////


/**
 * FIT Base Type enum
 */
const BaseType = {
    ENUM: 0x00,
    SINT8: 0x01,
    UINT8: 0x02,
    SINT16: 0x03,
    UINT16: 0x04,
    SINT32: 0x05,
    UINT32: 0x06,
    STRING: 0x07,
    FLOAT32: 0x08,
    FLOAT64: 0x09,
    UINT8Z: 0x0A,
    UINT16Z: 0x0B,
    UINT32Z: 0x0C,
    BYTE: 0x0D,
    SINT64: 0x0E,
    UINT64: 0x0F,
    UINT64Z: 0x10
};

const BaseTypeMask = 0x1F;

const BaseTypeDefinitions = {
    0x00: { size: 1, type: BaseType.ENUM, baseTypeEndianFlag: 0x00, invalid: 0xFF },
    0x01: { size: 1, type: BaseType.SINT8, baseTypeEndianFlag: 0x00, invalid: 0x7F },
    0x02: { size: 1, type: BaseType.UINT8, baseTypeEndianFlag: 0x00, invalid: 0xFF },
    0x03: { size: 2, type: BaseType.SINT16, baseTypeEndianFlag: 0x80, invalid: 0x7FFF },
    0x04: { size: 2, type: BaseType.UINT16, baseTypeEndianFlag: 0x80, invalid: 0xFFFF },
    0x05: { size: 4, type: BaseType.SINT32, baseTypeEndianFlag: 0x80, invalid: 0x7FFFFFFF },
    0x06: { size: 4, type: BaseType.UINT32, baseTypeEndianFlag: 0x80, invalid: 0xFFFFFFFF },
    0x07: { size: 1, type: BaseType.STRING, baseTypeEndianFlag: 0x00, invalid: 0x00 },
    0x08: { size: 4, type: BaseType.FLOAT32, baseTypeEndianFlag: 0x80, invalid: 0xFFFFFFFF },
    0x09: { size: 8, type: BaseType.FLOAT64, baseTypeEndianFlag: 0x80, invalid: 0xFFFFFFFFFFFFFFFF },
    0x0A: { size: 1, type: BaseType.UINT8Z, baseTypeEndianFlag: 0x00, invalid: 0x00 },
    0x0B: { size: 2, type: BaseType.UINT16Z, baseTypeEndianFlag: 0x80, invalid: 0x0000 },
    0x0C: { size: 4, type: BaseType.UINT32Z, baseTypeEndianFlag: 0x80, invalid: 0x00000000 },
    0x0D: { size: 1, type: BaseType.BYTE, baseTypeEndianFlag: 0x00, invalid: 0xFF },
    0x0E: { size: 8, type: BaseType.SINT64, baseTypeEndianFlag: 0x80, invalid: 0x7FFFFFFFFFFFFFFF },
    0x0F: { size: 8, type: BaseType.UINT64, baseTypeEndianFlag: 0x80, invalid: 0xFFFFFFFFFFFFFFFF },
    0x10: { size: 8, type: BaseType.UINT64Z, baseTypeEndianFlag: 0x80, invalid: 0x0000000000000000 },
};

const NumericFieldTypes = [
    "sint8",
    "uint8",
    "sint16",
    "uint16",
    "sint32",
    "uint32",
    "float32",
    "float64",
    "uint8z",
    "uint16z",
    "uint32z",
    "byte",
    "sint64",
    "uint64",
    "uint64z"
];

const FieldTypeToJsType = {
    "enum": "number",
    "sint8": "number",
    "uint8": "number",
    "sint16": "number",
    "uint16": "number",
    "sint32": "number",
    "uint32": "number",
    "string": "string",
    "float32": "number",
    "float64": "number",
    "uint8z": "number",
    "uint16z": "number",
    "uint32z": "number",
    "byte": "number",
    "sint64": "bigint",
    "uint64": "bigint",
    "uint64z": "bigint"
}

const BigIntFieldTypes = [
    "sint64",
    "uint64",
    "uint64z"
];

const FloatingPointFieldTypes = [
    "float32",
    "float64",
];

const FieldTypeToBaseType = {
    "enum": BaseType.UINT8,
    "sint8": BaseType.SINT8,
    "uint8": BaseType.UINT8,
    "sint16": BaseType.SINT16,
    "uint16": BaseType.UINT16,
    "sint32": BaseType.SINT32,
    "uint32": BaseType.UINT32,
    "string": BaseType.STRING,
    "float32": BaseType.FLOAT32,
    "float64": BaseType.FLOAT64,
    "uint8z": BaseType.UINT8Z,
    "uint16z": BaseType.UINT16Z,
    "uint32z": BaseType.UINT32Z,
    "byte": BaseType.BYTE,
    "sint64": BaseType.SINT64,
    "uint64": BaseType.UINT64,
    "uint64z": BaseType.UINT64Z
};

const BaseTypeToFieldType = {
    [BaseType.ENUM]: "enum",
    [BaseType.SINT8]: "sint8",
    [BaseType.UINT8]: "uint8",
    [BaseType.SINT16]: "sint16",
    [BaseType.UINT16]: "uint16",
    [BaseType.SINT32]: "sint32",
    [BaseType.UINT32]: "uint32",
    [BaseType.STRING]: "string",
    [BaseType.FLOAT32]: "float32",
    [BaseType.FLOAT64]: "float64",
    [BaseType.UINT8Z]: "uint8z",
    [BaseType.UINT16Z]: "uint16z",
    [BaseType.UINT32Z]: "uint32z",
    [BaseType.BYTE]: "byte",
    [BaseType.SINT64]: "sint64",
    [BaseType.UINT64]: "uint64",
    [BaseType.UINT64Z]: "uint64z",
};

const isNullOrUndefined = (obj) => {
    return obj == null;
};

const isObject = (obj) => {
    return typeof obj === "object";
};

const isBoolean = (obj) => {
    return "boolean" === typeof obj;
};

const isDate = (obj) => {
    return typeof obj === "object" && obj instanceof Date;
};

const isString = (obj) => {
    return typeof obj === "string";
};

const isBigInt = (obj) => {
    return typeof obj === "bigint";
};

const isNumeric = (obj) => {
    if (typeof obj === "number") {
        return !isNaN(obj) && isFinite(obj);
    }

    if (typeof obj === "bigint") {
        return true;
    }

    const num = parseFloat(obj);
    return !isNaN(num) && isFinite(num);
};

const isNotNumberStringDateOrBoolean = (obj) => {
    return !isNumberStringDateOrBoolean(obj);
};

const isNumberStringDateOrBoolean = (obj) => {
    if (isNullOrUndefined(obj)) {
        return false;
    }

    if (!isNumeric(obj) && !isDate(obj) && !isString(obj) && !isBoolean(obj)) {
        return false;
    }

    return true;
};

export default {
    BaseType,
    BaseTypeMask,
    BaseTypeDefinitions,
    NumericFieldTypes,
    BigIntFieldTypes,
    FloatingPointFieldTypes,
    FieldTypeToBaseType,
    BaseTypeToFieldType,
    FieldTypeToJsType,
    isNullOrUndefined,
    isObject,
    isBoolean,
    isDate,
    isString,
    isBigInt,
    isNumeric,
    isNumberStringDateOrBoolean,
    isNotNumberStringDateOrBoolean,
    MAX_FIELD_SIZE: 255,
    FIELD_DEFAULT_SCALE: 1,
    FIELD_DEFAULT_OFFSET: 0,
    MESG_DEFINITION_MASK: 0x40,
    LOCAL_MESG_NUM_MASK: 0x0F,
    ARCH_LITTLE_ENDIAN: 0x00,
    DEV_DATA_MASK: 0x20,
};
