/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////


import FIT from "./fit.js";

const FIT_EPOCH_MS = 631065600000;

const convertDateTimeToDate = (datetime) => {
    return new Date((datetime ?? 0) * 1000 + FIT_EPOCH_MS);
};

const convertDateToDateTime = (date) => {
    return (date.getTime() - FIT_EPOCH_MS) / 1000;
};

export default {
    FIT_EPOCH_MS,
    convertDateTimeToDate,
    convertDateToDateTime,
    FitBaseType: FIT.BaseType,
    BaseTypeToFieldType: FIT.BaseTypeToFieldType,
    FieldTypeToBaseType: FIT.FieldTypeToBaseType,
};
