name: Publish to npm

on:
  release:
    types: [created]

permissions:
  id-token: write # Required for OIDC provenance
  contents: read
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "22"
      - run: npm install --package-lock=false
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - name: Update npm
        run: npm install -g npm@11.5.1
      - run: npm --version
      - run: npm install --package-lock=false
      - name: Pack
        run: npm pack
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "*.tgz"
      - run: npm publish --provenance
